export const ADD_EXCEL_OPTION = "ADD_EXCEL_OPTION";
export const ACTIVE_OPTION = "ACTIVE_OPTION";
export const DOWNLOAD_OPTION = "DOWNLOAD_OPTION";
export const CUSTOMIZATION_OPTION = "CUSTOMIZATION_OPTION";
