export var searchFilterListInitConsignment: Array<any> = [
  {
    id: crypto.randomUUID(),
    valueName: "personelCode",
    label: "کد پرسنلی",
    isMain: true,
    isShow: false,
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    label: "شماره مرسوله",
    valueName: "code",
    type: "text",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "زمان ایجاد",
    valueName: "createdAt",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "وضعیت",
    valueName: "status",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "نوع مرسوله",
    valueName: "ConsignmentType",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تخصیص شده به سفر",
    valueName: "trip",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تعداد قطعات",
    valueName: "contentNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "نام مشتری",
    valueName: "customerName",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "آدرس گیرنده",
    valueName: "receiverAddress",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "پین کد مقصد",
    valueName: "destinationAddress",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "نام گیرنده",
    valueName: "receiverName",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تلفن گیرنده",
    valueName: "receiverPhone",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "وزن(کیلوگرم)",
    valueName: "Weight",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "آخرین بروز رسانی",
    valueName: "lastUpdate",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "هاب جاری",
    valueName: "currentHub",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "هاب توقف",
    valueName: "hubStop",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "هاب مبدا",
    valueName: "OriginHub",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "هاب مقصد",
    valueName: "destinationHub",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تاریخ زمان بندی مجدد",
    valueName: "RescheduleDate",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "مدت زمان تا تحویل",
    valueName: "DeliveryTime",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شهر",
    valueName: "city",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "جابجایی",
    valueName: "Movement",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "ارزش اظهاری",
    valueName: "DeclarativeValue",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "ارزش اظهاری",
    valueName: "DeclarativeValueStatus",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "جهت حرکت مرسوله",
    valueName: "directionOfMovementOfTheShipment",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "عنوان خطای ایجاد شده",
    valueName: "TheTitleOfTheGeneratedError",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "ادرس اینترنتی قبض صادره",
    valueName: "InternetAddressOfIssuedInvoice",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "وضعیت پرداخت",
    valueName: "PaymentStatus",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره سفر جمع آوری",
    valueName: "CollectionTripNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره سفر  رهسپاری",
    valueName: "TravelNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره سفر تحویل",
    valueName: "DeliveryTripNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "هاب بعدی",
    valueName: "nextHub",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره کیسه ",
    valueName: "bagNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "یادداشت های آخرین رویداد",
    valueName: "NotesOfTheLastEvent",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "فرستنده",
    valueName: "sender",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره قفسه",
    valueName: "shelfNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تعداد مراحعه جهت تحویل",
    valueName: "NumberReferralsForDelivery",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تعداد مراجعه جهت جمع آوری",
    valueName: "NumberOfReferralsForCollection",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "آخرین دلیل عدم تحویل موفق",
    valueName: "TheLastReasonForTheUnsuccessfulDelivery",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "آخرین دلیل عدم جمع آوری موفق",
    valueName: "TheLastReasonForNotCollectingSuccessfully",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "وزن مبنای محاسبه",
    valueName: "CalculationBasisWeight",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "وزن حجمی",
    valueName: "WeightVolumetric",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تاریخ تسویه حساب",
    valueName: "SettlementDate",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "مسئول ارزش گذاری نهایی مرسوله",
    valueName: "ResponsibleForTheFinalValuationOfTheShipment",
    type: "time",
  },

  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "نوع تحویل",
    valueName: "DeliveryType",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "پین کد فرستنده",
    valueName: "PinCodeOfTheSender",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "آدرس کد فرستنده",
    valueName: "SenderCodeAddress",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شهر فرستنده",
    valueName: "senderCity",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "تلفن فرستنده",
    valueName: "SenderPhone",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "نوع سوریس",
    valueName: "SourisType",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره صورت حساب",
    valueName: "AccountNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "برنامه ریزی شده در تاریخ",
    valueName: "ScheduledOnThedate",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "وضعیت QC",
    valueName: "statusQC",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "پرداخت با اسکناس",
    valueName: "PaymentByBanknote",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "IMEI1",
    valueName: "IMEI1",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "دستگاه1",
    valueName: "device1",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "IMEI2",
    valueName: "IMEI2",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "دستگاه2",
    valueName: "device2",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "IMEI3",
    valueName: "IMEI3",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "دستگاه3",
    valueName: "device3",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "شماره سیمکارت",
    valueName: "SIMCardNumber",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "منطقه گیرنده",
    valueName: "recipientArea",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "منطقه فرستنده",
    valueName: "SenderArea",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "ناحیه گیرنده",
    valueName: "receiverArea",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "ناحیه فرستنده",
    valueName: "senderArea",
    type: "time",
  },
  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "بازه زمانی تحویل",
    valueName: "DeliveryTimePeriod",
    type: "time",
  },

  {
    id: crypto.randomUUID(),
    isMain: false,
    isShow: false,
    isRequire: false,
    label: "مبلغ قابل پرداخت",
    valueName: "TheAmountPayable",
    type: "time",
  },
];
